(defpackage #:mcparen
  (:use #:cl)
  (:import-from #:bordeaux-threads
                #:condition-notify
                #:condition-wait
                #:current-thread
                #:destroy-thread
                #:join-thread
                #:make-condition-variable
                #:make-lock
                #:make-thread
                #:thread-alive-p
                #:with-lock-held)
  (:import-from #:serapeum
                #:->)
  (:export #:*json-maximum-aggregate-string-characters*
           #:*json-maximum-array-elements*
           #:*json-maximum-depth*
           #:*json-maximum-nodes*
           #:*json-maximum-number-characters*
           #:*json-maximum-object-key-characters*
           #:*json-maximum-object-members*
           #:*json-maximum-string-characters*
           #:*mcp-pagination-maximum-aggregate-bytes*
           #:*mcp-pagination-maximum-aggregate-nodes*
           #:*mcp-pagination-maximum-items*
           #:*mcp-pagination-maximum-pages*
           #:*mcp-pagination-restart-limit*
           #:make-mcp-client
           #:make-mcp-stdio-transport
           #:make-mcp-streamable-http-transport
           #:json-false-value
           #:json-null-value
           #:json-object
           #:json-true-value
           #:mcp-call-result
           #:mcp-call-result-content
           #:mcp-call-result-error-p
           #:mcp-call-result-raw
           #:mcp-call-result-structured-content
           #:mcp-call-result-text
           #:mcp-client
           #:mcp-client-call-tool
           #:mcp-client-client-capabilities
           #:mcp-client-client-info
           #:mcp-client-close
           #:mcp-client-connect
           #:mcp-client-connected-p
           #:mcp-client-detach
           #:mcp-client-get-prompt
           #:mcp-client-instructions
           #:mcp-client-list-prompts
           #:mcp-client-list-resource-templates
           #:mcp-client-list-resources
           #:mcp-client-list-tools
           #:mcp-client-ping
           #:mcp-client-protocol-version
           #:mcp-client-read-resource
           #:mcp-client-server-capabilities
           #:mcp-client-server-info
           #:mcp-client-startup-timeout
           #:mcp-client-tool-timeout
           #:mcp-client-transport
           #:mcp-content-block-type
           #:mcp-error
           #:mcp-error-message
           #:mcp-http-transport-connect-timeout
           #:mcp-http-transport-headers-function
           #:mcp-http-transport-maximum-message-characters
           #:mcp-http-transport-protocol-version
           #:mcp-http-transport-session-identifier
           #:mcp-http-transport-url
           #:mcp-message-too-large
           #:mcp-message-too-large-limit
           #:mcp-message-too-large-source
           #:mcp-protocol-error
           #:mcp-protocol-error-method
           #:mcp-protocol-error-payload
           #:mcp-rpc-error
           #:mcp-rpc-error-code
           #:mcp-rpc-error-data
           #:mcp-session-expired
           #:mcp-stdio-transport
           #:mcp-stdio-transport-arguments
           #:mcp-stdio-transport-command
           #:mcp-stdio-transport-directory
           #:mcp-stdio-transport-environment-function
           #:mcp-stdio-transport-maximum-message-characters
           #:mcp-stdio-transport-stderr-text
           #:mcp-streamable-http-transport
           #:mcp-timeout
           #:mcp-timeout-operation
           #:mcp-timeout-seconds
           #:mcp-tool
           #:mcp-tool-annotations
           #:mcp-tool-description
           #:mcp-tool-destructive-p
           #:mcp-tool-input-schema
           #:mcp-tool-name
           #:mcp-tool-output-schema
           #:mcp-tool-raw
           #:mcp-tool-read-only-p
           #:mcp-tool-title
           #:mcp-transport
           #:mcp-transport-close
           #:mcp-transport-detach
           #:mcp-transport-error
           #:mcp-transport-error-cause
           #:mcp-transport-error-transport
           #:mcp-transport-notify
           #:mcp-transport-open
           #:mcp-transport-open-p
           #:mcp-transport-request
           #:mcp-transport-set-protocol-version
           #:with-mcp-client
           #:with-open-mcp-transport))
